version : "3.5"
services :

 waiter:
  build: ./waiter
  container_name: waiter
  image: 'waiter:1.0'
  ports:
    - "8080:8080"
  environment:
    KAFKA_SERVER: kafka:9092
  depends_on: 
    - kafka
  restart: always

 bartender:
  build: ./bartender
  container_name: bartender
  image: 'bartender:1.0'
  environment:
    KAFKA_SERVER: kafka:9092
  depends_on: 
    - kafka
  restart: always

 zookeeper:
  image: 'bitnami/zookeeper:3.7.0'
  container_name: zookeeper
  ports:
    - "2181:2181"
  environment:
    - ALLOW_ANONYMOUS_LOGIN=yes

 kafka:
   image: 'bitnami/kafka:2.8.0'
   container_name: kafka
   ports:
     - '9092:9092'
     - '9093:9093'
   environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
   depends_on:
     - zookeeper
