apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bartender
  name: bartender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bartender
  strategy: {}
  template:
    metadata:
      labels:
        app: bartender
    spec:
      containers:
        - env:
            - name: KAFKA_SERVER
              value: kafka:9092
          image: bartender:1.0
          name: bartender
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bartender
  name: bartender
spec:
  ports:
  - name: client
    port: 2181
  selector:
    app: bartender
status:
  loadBalancer: {}
